### ISSUE TITLE
tarball missing and example invalid

### ISSUE THREAD

**Issue by gretel** [dc740/django-coveragepy-github-action#4]
```
Download action repository 'actions/python-django-coverage-gitHub-action@v1'
##[error]An action could not be found at the URI 'https://api.github.com/repos/actions/python-django-coverage-gitHub-action/tarball/v1'
```

the example has no valid semantics (two uses of `uses`).

**Comment by leeroywking** [comment]
+1

**Comment by dc740** [comment]
thanks for the report. Feel free to send a PR. I don't have time to fix it myself right now, but I'll make time to review the PR and create a new tag with a fixed version.

**Comment by dc740** [comment]
OK, this was way more simple than I originally thought. The example is just wrong. There is no v1 tag. there is only `0.9` . I'll probably bring in changes from other forks before releasing `v1`. but I updated the example in the meantime.

**Comment by gretel** [comment]
@dc740 thank you
